# Spam Detection: Naive Bayes vs SVM

**Student Name:** _________________  
**Date:** _________________

In this project, you'll:
1. Load a spam email dataset
2. Train a Naive Bayes classifier
3. Train an SVM classifier
4. Compare the results

<small><i>Note</i>: This project was created with the assistance of AI</small>

---

## Step 1: Import Libraries and Load Data

In [48]:
# Import libraries
import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)

In [49]:
# Load the dataset
data = pd.read_csv('../data/spam_data.csv')

# Display first few rows
data.head()

word_free  word_money  word_winner  word_click  word_urgent  \
0   0.116603    0.081405     0.248621    0.107026     0.084280   
1   0.150017    0.202468     0.071720    0.227412     0.228002   
2   0.009429    0.190923     0.094307    0.152571     0.272270   
3   0.085727    0.129830     0.205633    0.099737     0.016976   
4   0.050113    0.050286     0.011001    0.220921     0.199141   

   num_exclamation  num_dollar  num_capitals  email_length  has_link  is_spam  
0         0.162809    0.042277      0.240659    101.836546  0.296066        0  
1         0.093779    0.123205      0.062907     90.571442  0.193681        0  
2         0.074788    0.123115      0.226665    130.369345  0.023094        0  
3         0.112176    0.283335      0.192520     98.526674  0.189685        0  
4         0.142389    0.253251      0.241701     96.637459  0.260481        0

## Step 2: Preprocessing the Data
* Clean the data
* Split the data into training and test sets.
* Feature Scaling

In [50]:
data.isna().sum()

word_free          0
word_money         0
word_winner        0
word_click         0
word_urgent        0
num_exclamation    0
num_dollar         0
num_capitals       0
email_length       0
has_link           0
is_spam            0
dtype: int64

In [51]:
data.describe()

word_free   word_money  word_winner   word_click  word_urgent  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.324655     0.437897     0.444648     0.327555     0.448487   
std       0.276739     0.416377     0.429590     0.266253     0.429160   
min       0.001814     0.000009     0.000003     0.001728     0.000040   
25%       0.103749     0.130491     0.133985     0.123341     0.125848   
50%       0.232671     0.256609     0.246666     0.241799     0.250986   
75%       0.492580     0.715676     0.698216     0.515019     0.756558   
max       0.997347     1.498341     1.491796     0.998332     1.497016   

       num_exclamation   num_dollar  num_capitals  email_length     has_link  \
count      1000.000000  1000.000000   1000.000000   1000.000000  1000.000000   
mean          0.562027     0.569642      0.329246     83.687840     0.321640   
std           0.582346     0.595018      0.276511     32.841447     0.265409   
min           0.000068     0.000179      0.000470     20.271028     0.000334   
25%           0.129044     0.118774      0.119615     58.649876     0.125624   
50%           0.260757     0.247139      0.235900     81.591240     0.235755   
75%           0.991942     1.029110      0.499580    105.938149     0.471724   
max           1.998248     1.990861      0.999604    149.946068     0.995018   

           is_spam  
count  1000.000000  
mean      0.400000  
std       0.490143  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

There doesn't seem to be any missing data or any data out of whack, other than email length not being normalized. (which I will do below). 

In [52]:
email_max = data["email_length"].max()
email_min = data["email_length"].min()

data["email_length"] = (data["email_length"] - email_min) / (email_max - email_min)
data.describe()

word_free   word_money  word_winner   word_click  word_urgent  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.324655     0.437897     0.444648     0.327555     0.448487   
std       0.276739     0.416377     0.429590     0.266253     0.429160   
min       0.001814     0.000009     0.000003     0.001728     0.000040   
25%       0.103749     0.130491     0.133985     0.123341     0.125848   
50%       0.232671     0.256609     0.246666     0.241799     0.250986   
75%       0.492580     0.715676     0.698216     0.515019     0.756558   
max       0.997347     1.498341     1.491796     0.998332     1.497016   

       num_exclamation   num_dollar  num_capitals  email_length     has_link  \
count      1000.000000  1000.000000   1000.000000   1000.000000  1000.000000   
mean          0.562027     0.569642      0.329246      0.489044     0.321640   
std           0.582346     0.595018      0.276511      0.253260     0.265409   
min           0.000068     0.000179      0.000470      0.000000     0.000334   
25%           0.129044     0.118774      0.119615      0.295962     0.125624   
50%           0.260757     0.247139      0.235900      0.472876     0.235755   
75%           0.991942     1.029110      0.499580      0.660629     0.471724   
max           1.998248     1.990861      0.999604      1.000000     0.995018   

           is_spam  
count  1000.000000  
mean      0.400000  
std       0.490143  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [53]:
y = data["is_spam"]
data.drop(columns=["is_spam"], inplace=True)
X = data

In [54]:
# Split the data using a random state of 42 for reproducibility
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

## Step 3: Train Naive Bayes Classifier

In [55]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(X_train, y_train.ravel())
nb_model

/tmp/ipykernel_41415/3757815442.py:4: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  nb_model.fit(X_train, y_train.ravel())


GaussianNB()

In [56]:
y_pred = nb_model.predict(X_test)

Display your confusion matrix and your classification report.

In [57]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[113   0]
 [  0  87]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       113
           1       1.00      1.00      1.00        87

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



## Step 4: Train k-Nearest Neighbors Classifier

In [58]:
from sklearn.neighbors import KNeighborsClassifier

k = 17

knn_class = KNeighborsClassifier(n_neighbors=k, metric='euclidean')
knn_class.fit(X, y)

KNeighborsClassifier(metric='euclidean', n_neighbors=17)

In [59]:
y_pred = knn_class.predict(X_test)

Display your confusion matrix and classification report.

In [60]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[113   0]
 [  0  87]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       113
           1       1.00      1.00      1.00        87

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



## Step 5: Train SVM Classifier

In [61]:
from sklearn.svm import LinearSVC

svm_class = LinearSVC(C=1, loss="hinge")
svm_class.fit(X, y)

LinearSVC(C=1, loss='hinge')

In [62]:
y_pred = svm_class.predict(X_test)

Display your confusion matrix and your classification report.

In [63]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[113   0]
 [  0  87]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       113
           1       1.00      1.00      1.00        87

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



## Step 6: Compare the Models
* Create graphs that compare model results
* Make calculations to compare model results

Discuss the results of your comparison.

---

## Step 7: Answer Discussion Questions

Based on your results, answer the following questions:

### Question 1: Which model performed better overall? Why do you think so?

**Your Answer:**

_[Write your answer here]_

---

### Question 2: What is the difference between accuracy and precision? Which is more important for spam detection?

**Your Answer:**

_[Write your answer here]_

---

### Question 3: When would you choose Naive Bayes over kNN or SVM in a real-world application?

**Your Answer:**

_[Write your answer here]_

---

### Question 4: What are the key assumptions of Naive Bayes? Do you think they hold true for this spam detection problem?

**Your Answer:**

_[Write your answer here]_

---

### Question 5: How did you determine your value for $k$ in the kNN model?

**Your Answer:**

_[Write your answer here]_

---

## Summary

In this project, you:
- ✅ Loaded and split a spam detection dataset
- ✅ Trained a Naive Bayes classifier
- ✅ Trained an SVM classifier  
- ✅ Compared both models using multiple metrics
- ✅ Analyzed the results

**Key Takeaways:**
1. Different algorithms can produce different results on the same data
2. Multiple metrics (accuracy, precision, recall) give a complete picture
3. Both Naive Bayes and SVM are effective for classification tasks
4. The choice of algorithm depends on the specific requirements of your problem